hl.config({
	input = {
		kb_layout = "de",
		follow_mouse = 2,
		touchpad = {
			natural_scroll = false,
		},
		sensitivity = 0,
	},
})

hl.config({
	autogenerated = false,
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		on_focus_under_fullscreen = 1,
		focus_on_activate = true,
	},

	cursor = {
		zoom_rigid = true,
		zoom_detached_camera = false,
	},

	general = {
		gaps_in = 4,
		gaps_out = 6,
		border_size = 2,
		col = {
			active_border = { colors = { "rgba(88C0D0ee)", "rgba(5E81ACee)" }, angle = 45 },
			inactive_border = "rgba(434C5Eaa)",
		},
		layout = "master",
		-- layout = dwindle
	},

	decoration = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		rounding = 10,
		dim_inactive = false,
		dim_strength = 0.2,
		blur = {
			enabled = true,
			size = 4,
			passes = 2,
			new_optimizations = true,
		},
		shadow = {
			enabled = true,
			range = 10,
			render_power = 3,
			color = 0xee1a1a1a,
			color_inactive = 0x33000000,
		},
	},
	animations = {
		enabled = false,
	},
	dwindle = {
		preserve_split = true,
	},
	xwayland = {
		force_zero_scaling = true,
	},
})

hl.layer_rule({ match = { namespace = "waybar" }, blur = true, ignore_alpha = 0.9 })

hl.workspace_rule({ workspace = "w[tv1]", gaps_in = 0, gaps_out = 0 })
hl.workspace_rule({ workspace = "f[tv1]", gaps_in = 0, gaps_out = 0 })

hl.window_rule({
	name = "fullscreen-borderless",
	match = {
		float = false,
		workspace = "w[tv1]",
	},
	border_size = 0,
	rounding = 0,
})

hl.window_rule({
	name = "only-window-borderless",
	match = {
		float = false,
		workspace = "f[tv1]",
	},
	border_size = 0,
	rounding = 0,
})

hl.window_rule({
	name = "screenkey",
	match = { title = "^([Ss]creenkey)" },
	float = true,
	move = "78% 87%",
	size = "20% 10%",
	monitor = 1,
	opaque = true,
	no_focus = true,
	no_initial_focus = true,
})

hl.window_rule({
	name = "terminal",
	match = { class = "(([Kk]itty)|([Gg]hostty)|([Aa]lacritty))$" },
	workspace = 1,
})

hl.window_rule({
	name = "browser",
	match = { class = "(([Zz]en)|(zen-browser))$" },
	workspace = 2,
})

hl.window_rule({
	name = "sioyek",
	match = { class = "sioyek" },
	workspace = 3,
})

hl.window_rule({ match = { class = "(obsidian)" }, workspace = "4" })
hl.window_rule({ match = { class = "([Zz]otero)" }, workspace = "4 silent" })
hl.window_rule({ match = { class = "([Ss]potify)" }, workspace = "5 silent" })

hl.window_rule({
	name = "waylandbridge",
	match = { class = "^(xwaylandvideobridge)$" },
	opacity = 0.0,
	no_anim = true,
	no_focus = true,
	no_initial_focus = true,
})

hl.permission({ binary = "/usr/bin/grim", type = "screencopy", mode = "allow", allow = "true" })
hl.permission({
	binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland",
	type = "screencopy",
	mode = "allow",
	allow = "true",
})

hl.env("CLUTTER_BACKEND", "wayland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("WLR_NO_HARDWARE_CURSORS", "0")
hl.env("WLR_BACKEND", "vulkan")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("GDK_BACKEND", "wayland")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")

-- AUTO EXECS
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("dunst")
	hl.exec_cmd("spotify-launcher")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("zotero --headless")
end)

require("keybinds.keybind")

require("device.device")

require("monitors")
