#! /bin/bash
tempfilename=~/temp/$(date +%s).jpg
grim -g "$(slurp)" $tempfilename
if [ -f "$tempfilename" ] ; then
    # zenity --question --text "Copy to clipboard?"
    # toClipboard=$?
    # if [ $toClipboard -eq 0 ] ; then
    #     wl-copy < $tempfilename
    # fi
    mv $tempfilename "$(zenity --file-selection --filename=~/Pictures/screenshot.jpg --save)"
fi
if [ -f "$tempfilename" ] ; then
    rm $tempfilename
fi
