#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected="pwa-$1"
else
    selected=$(find ~/.local/share/applications/pwa-* | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected")

gtk-launch $selected_name &
