live_config_reload = true

import = ["~/.config/alacritty/nord-v3.toml"]

[window]
opacity = 0.9

[window.padding]
x = 10
y = 5

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Always"
