require("daniel.config.set")


require("daniel.config.alpha")
require("daniel.config.autocommands")
require("daniel.config.autopairs")
require("daniel.config.bufferline")
require("daniel.config.colorizer")
require("daniel.config.cmp")
require("daniel.config.illuminate")
require("daniel.config.indentline")
require("daniel.config.lspconfig")
require("daniel.config.neogit")
require("daniel.config.project")
require("daniel.config.remap")
require("daniel.config.telescope")
require("daniel.config.vimtex")
