require("daniel.set")
-- require("daniel.remap")
require("daniel.packer")
require("daniel.latex")
require("daniel.config")
require("daniel.snippet-store")
-- require("daniel.alpha")
-- require("daniel.colorizer")
-- require("daniel.neogit")
